name: User Story Template
description: This template is to create user stories
title: 'As a...'
labels: ['user story']
projects: ["ublibraries/6"]
assignees: 
  - Martinsc8
body:
  - type: markdown
    attributes:
      value: |
        Thanks for adding a user story!
  - type: textarea
    id: user-story
    attributes:
      label: Please describe your story...
    validations:
      required: true
  - type: input
    id: who
    attributes:
      label: Who is this user story concerning?
  - type: input
    id: what
    attributes:
      label: What is the who trying to do?
  - type: input
    id: why
    attributes:
      label: Why does the who need to do the what?
